FROM postgis/postgis:16-3.4
COPY 1-init-keycloak-db.sh /docker-entrypoint-initdb.d/                                                            
RUN chmod +x /docker-entrypoint-initdb.d/1-init-keycloak-db.sh